### ISSUE TITLE
Scrap case numbers from a text file or similar

### ISSUE THREAD

**Issue by marolio** [gentlespoon/USCIS-Case-Status-Checker#10]
Hi!

Would it be possible to import a txt file or something with predefined case numbers? Because im focused only in a certain type of case and I have the list of only those cases. This way I would be able to check a list of around 25000 cases without scrapping the around 700000 cases in between and being blacklisted from the website

Thank you a lot in a advance!

**Comment by gentlespoon** [comment]
Implemented in v2020.02.01
