### ISSUE TITLE
Can you confirm the json url 

### ISSUE THREAD

**Issue by famictech2000** [gentlespoon/USCIS-Case-Status-Checker#8]
Are you pulling the information from a json file?

If so, can you confirm the url for that json feed?

**Comment by gentlespoon** [comment]
It is not pulling any information from a json file.

**Comment by famictech2000** [comment]
How does it get the information then?

**Comment by gentlespoon** [comment]
https://egov.uscis.gov/casestatus/mycasestatus.do?appReceiptNum=<yourReceiptNumber>

**Comment by famictech2000** [comment]
Can I ask how you determined the url specifically how did you know appReceiptNum was the variable to pass?

**Comment by gentlespoon** [comment]
Open the browser console and switch to network tab.
Check a few receipt number, observe the URL it requests, and you will find the variable part easily.

**Comment by famictech2000** [comment]
I am trying to do the same for this https://github.com/gr2m/uscis-service-center-processing-times, but what I see in the Network tab doesn't work?!

**Comment by gentlespoon** [comment]
If the URL is correct, check if you are using the correct request method (GET vs. POST) also check if you left any required parameter or header out.
